apiVersion: v1
kind: Service
metadata:
  name: majestic-bohr-ba7ba4674f-srv
  namespace: apps-prod
spec:
  selector:
    app: majestic-bohr-ba7ba4674f
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP